files: ^src/.*\.py$
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.7
  hooks:
    # Run the linter.
    -   id: ruff
        args: [--fix]
    # Run the formatter.
    -   id: ruff-format
- repo: https://github.com/semgrep/semgrep
  rev: "v1.120.0"
  hooks:
    - id: semgrep
      args:
        - --config
        - p/ci
        - --error
        - --skip-unknown-extensions
        - --metrics
        - 'off'
- repo: https://github.com/Yelp/detect-secrets
  rev: "v1.5.0"
  hooks:
  - id: detect-secrets
- repo: local
  hooks:
    - id: mypy
      name: mypy bash script
      entry: ./pre-commit-mypy.sh
      language: system
      types: [python]
    -   id: run-tests
        name: run tests
        entry: .venv/bin/pytest
        language: system
        pass_filenames: false
    -   id: check-coverage
        name: Check Coverage
        entry: .venv/bin/python tests/test_coverage.py
        language: python