repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.8
  hooks:
    # Run the linter.
    - id: ruff
      args: [--fix]
      types: [python]
    # Run the formatter.
    - id: ruff-format
      types: [python]
- repo: local
  hooks:
  - id: mypy
    name: mypy
    entry: bash -c 'mypy --python-executable .venv/bin/python src/'
    language: system
    pass_filenames: false
    types: [python]
  - id: run-tests
    name: run tests
    entry: .venv/bin/pytest
    language: system
    pass_filenames: false
    types: [python]
  - id: check-coverage
    name: Check Coverage
    entry: .venv/bin/python tests/test_coverage.py
    language: python
    pass_filenames: false
    types: [python]
- repo: https://github.com/semgrep/semgrep
  rev: "v1.121.0"
  hooks:
    - id: semgrep
      args:
        - --config
        - p/ci
        - --error
        - --skip-unknown-extensions
        - --metrics
        - 'off'
- repo: https://github.com/Yelp/detect-secrets
  rev: "v1.5.0"
  hooks:
  - id: detect-secrets