name: Ruff Lint and Format

permissions:
  contents: read

on:
  pull_request:

jobs:
  ruff:
    name: Ruff Lint and Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Ruff
        uses: astral-sh/ruff-action@v3

      - name: Run Ruff Format
        run: ruff format --check --diff
